apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
    namespace: default
stringData:
    config.toml: ENC[AES256_GCM,data:XZmFHgeqnnDftyV90OkuKTQvj3yu1ziKXdHLq/IJ4S1jTBM+CSWVIkkV9sL+/fgjZpwrvTwy2E5+nDLGdPypAZu8jOB6KCUBTz6z9xylkSKxR2bHX0aTc7egRujY4AYixDXDSBX/O0vq/YHWT+CB9RvTUng2tBVp7e1GlJyiOpBYKlj+PdQgNetOhQQ7IpovUQpbvL/is2EcGttoOfsa4mJHFaqIm2QsBVKpApE1LYzZc39OC8ygNaq3IocTdaVSaq35deOwg0YggmeXBUBK+xCQZ4XYtm9JrAqOG5+JvEkqrhsinsXnaV0S1lNPKDv3un/BwBoafL3NS4YdoeckTvBtj3X/pnRp0+kVuIWkDlf1Do5L5QB9aGB0EAvFNwxejg==,iv:Lvr9SmS5wNVnjETiFG3cuPLmK7Qx7XTT9FqsXk0GkdM=,tag:sqbZmOKsRFOEHQSsp+f0sw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aqz4ykzkneymnm277lgqzcnx2xqapvjpazy42prvxc0tmqzs7s4szgy2hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbUNLdlIyNUNmVkpiR2tD
            TEV1cVZRbTNnODJYaEZFc0s3OHpGL2VaeHc0CjhuRE1Od1FueU9hRkRPam1lV0o4
            RitUSkRwWnRXeHhiRng3dmRCaFlDdjAKLS0tIEZjUWVRVUNGZHJkSE9Ha0MyTVNW
            YUVLU2xiTHl3RkhBY3RxVm10WkUzTUUK2KkQKzam2/u5JVQCZWTvs9OyMx8aL0Dk
            0aBYMDoqcgNav7Y69j/ve04zTuaWeeIjnyFR/QorzCi9m41/Fwf9uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T02:33:20Z"
    mac: ENC[AES256_GCM,data:iwYb26pkNJ7VpNLld+e6AU5J8+HVoUYQUQdMGm6TfPBP9tzOS+8jj0yMaWNvT0xZAt2cB9yE16y9DmifHad/sOBk3ahd4AuVJtRxx4MN2BcEfnXV589gtWSF2HZ5AGeP3p5j9AnFc1isTz8tg4f0Slyze//U5yHRFgb6svcMjzc=,iv:JK73pVvzFAyKspluyrUOsRVI7Y5FGT18vWTzhvYPuQw=,tag:W4sHS7HOJliAtKttrBGWtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
