apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:zTZbDvllNBUETssxTEiRt6xvGlF7WBIK,iv:pfkFRgU9mBnSHrx+44cMF6x2cTiY7V9EH6RvsdixCe4=,tag:0fDh7t+kvgRpxV4MCI0ZDQ==,type:str]
    admin-user: ENC[AES256_GCM,data:83qrrUk=,iv:+g9tuuxjhSDXxhRS0gbqpeFhKKFhN5nJcGHQTxhce5k=,tag:/yXDlvUIW5Od7LiF6dQnKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aqz4ykzkneymnm277lgqzcnx2xqapvjpazy42prvxc0tmqzs7s4szgy2hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaczNVMjZRSnkvWlFTbmZI
            K1hNSExpemFQRnpYZGRMLzE1VEFHaVQ4a25ZCitabCtIZmgxMGM3emJ4Qjg4dTZx
            MVhXTmZCR2VOZW43TDBuQzNiR0hoS3MKLS0tIElJU29VeU9Jd3RoNzY1L01kZVRD
            MU5Gc3l5Tjk5emxsSlZUTHljSXVmYVEKy5tXLL+2cR87KIAAhQpR/mCcljEx/a+T
            QlzYznsXtT4Unbmz34Lw0ZDjQxcTO8MdoJ5ccidzEsS9quSediyFMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T02:33:15Z"
    mac: ENC[AES256_GCM,data:tEHKdVv2YpZ9nfPlH7W+EG0icnvMpk4tCv1iOlA5CRpyZZi+eU5ggl0AsvN80q5fIzNl4VA25MnKWIVzf45QBlmcb0x7G7KaEKQh61lEhRUxYJSy0Y793Qz+Owzw9mqzHJ4EvqbOv9/VZve02qBYdbX17sTtpi/GXfGFHD887gA=,iv:HiPzG4nrNoBKmbNQTJW9E39Wytnm6PymWNkKdPicBNQ=,tag:RsLWxNJzz8ummPVwHNOc/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
