apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Soj09xsoU4sPhe63WiDHm96BOoXzgyY9lTyLz8vqiHTUar77P0BJHQ==,iv:3Z8IKpbs3bL5orIKIogWAfqoSdhzNtVWpqG11VwMR5A=,tag:KN12zKx7k6wDusIYHBKq0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aqz4ykzkneymnm277lgqzcnx2xqapvjpazy42prvxc0tmqzs7s4szgy2hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYlJITmFYTFBYTTlGYTFD
            OExiemlhSE9ISWJrVkE3bnMvT25DM1QrV0Z3CnZVNEFLR0NZOW1HWGNWYm9xQjFh
            dzlKbHROU0FkbUFDbVJmbXQrZkNVbEUKLS0tIDIrN28zVnJiVHBwbnNqaFFoSFUw
            eFY1VFQvTDcrNm1yaU1QS2M5RmxXTk0KzBk5C5qz7ASGtLMWxCxks43qesiPwfvL
            RcQZYsKsemwJ8vnVBGNb/Qt89yfNqy4rRRKfrVVInDxgw3kID9BCjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T02:33:12Z"
    mac: ENC[AES256_GCM,data:MpcmmKO3jHKd5b3N6FmtpDBQInFFPTYwK7dtxxXioTYhT67e4cTvrf9l3SWGPkFgOdwJGNT11ve81iq9GtHmRsQlRm1jTLnZsl4o4eUQ/yqWZtNfCBFSFkFarSKAQW7UEBjPt5lrUcOuxpwaa7tI67OBtvUurF6s41Vxlfl1bkQ=,iv:P44fWAshyEq20LYk9h10EfJfN8EFwPOettLA0oSMmvs=,tag:moms+78r3hnsDHCYRp4yGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
