---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-share
provisioner: nfs.csi.k8s.io
parameters:
  server: ${SECRET_NAS_ADDR}
  share: ${SECRET_NFS_SHARE}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
