apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:0m15CchzZADwT1sO,iv:dsveHmVW/Jczh/tKvtmFqqehL9iEGZzaAxVV96S12ng=,tag:0P++XmDGrBZdcLNJDqTwhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aqz4ykzkneymnm277lgqzcnx2xqapvjpazy42prvxc0tmqzs7s4szgy2hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYVNRaXJDS1A2QmdPSHl6
            SmdBVnJra3ZHUXNOd2VVRTd3d1JteUg1ZWhNCndoTHgrcHBqdWI5anJTKzhzazc1
            RXVFYVZnN0NsS2wvdWMyZytuUnIzMDgKLS0tIE1NU2VMZ2RDeGtNM3ZMUm1FNzVG
            QTlpTlRuWnNoeitqSHE0Z1dwaElkWFUK1sh/HGVfSq3ApDd+LzWiMyr99ZFIj1Dg
            AOqnehTsL336Cj7v7h8upVIc/AnjPYlo4ZOboJ84ZZVcxEiQ8sscUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T02:33:12Z"
    mac: ENC[AES256_GCM,data:gEI83dxdyoTmQz+kYX2F4673mzrfH0OSPTEViCHhCGQJC7gbqj1MZSCcOGo69aJEunaRysI/lz8ouSU781L5ii5po0zYot6uFAz9MOAMwmojTGjfQ+aox0FhlUqu5bplTXa+4s3XR7Bj7bWUQQZr5GbBJQhEbDAC7AYYhAGhWkM=,iv:HeRREGZa8xTX3UnlNd8kLf6ujXRdWLTCo8Mhv6CDRTk=,tag:AfNEm3zHYisCP+pV5DNWFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
