---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Pacific/Auckland"
  COREDNS_ADDR: "10.245.0.10"
  KUBE_VIP_ADDR: "192.168.1.248"
  CLUSTER_CIDR: "10.244.0.0/16"
  SERVICE_CIDR: "10.245.0.0/16"
  NODE_CIDR: "192.168.1.0/24"
