---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.6.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    defaultSettings:
      # backupTarget: s3://longhorn@weur/
      # backupTargetCredentialSecret: longhorn-secret
      defaultReplicaCount: 3
      backupstorePollInterval: 0
      createDefaultDiskLabeledNodes: false
      restoreVolumeRecurringJobs: true
      priorityClass: high-priority
      defaultDataPath: /var/lib/longhorn/
      defaultDataLocality: best-effort
      replicaAutoBalance: best-effort
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 25
      guaranteedEngineManagerCPU: 15
      guaranteedReplicaManagerCPU: 15
      orphanAutoDeletion: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultLonghornStaticStorageClass: longhorn
      allowVolumeCreationWithDegradedAvailability: false
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/appName: "Longhorn"
        hajimari.io/enable: "true"
        hajimari.io/icon: "mdi:harddisk"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
